create database university;
use university;
create table admin(id int,uname varchar(20),pwd varchar(20));
insert into admin values(01,"Albin","albin@12");
insert into admin values(02,"Abin","abin@34");
create table student(roll_num int,name varchar(20),branch varchar(20),father varchar(20),gender varchar(20));
insert into student values(01,"arjun","cs","ramchandran","m");
insert into student values(02,"rahul","cs","rajeendran","m");
insert into student values(03,"rizwan","ee","akbar","m");
create table details(roll_num int,laca int,ls int,dp int,ema int);
insert into details values(01,45,46,47,48);
insert into details values(02,41,42,43,44);
insert into details values(03,36,37,38,39); 
select *from details;
create database school;
select *from student;
use school;
create table Students(Roll_No int,Name varchar(50),Department varchar(50),Gender varchar(20),Father_Name varchar(50),District varchar(50));
select * from Students;
use school;
create table Registration(uname varchar(40),password varchar(20),email varchar(30),phone varchar(40));
select * from Registration;
select *from admin; 
SET SQL_SAFE_UPDATES=0;
delete from  details where roll_num=null;
delete from details where laca='';
alter table details (rol_num int not null);